# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17bc804f75ba1a5d4244308b26a71195bf37dac9883e560eb8ca123a6e829ec633d13580dcf062e7a5d387ada086b915e6039d5ea92e4f642f2d568590d7b262

test:
  secret_key_base: 69375f106d191ddf3c700d56d391da1dcfef614897b02c4d8eec16265d4b57214772a037821689c107a090828c6b329fdd9336a59d7d36a4efa94f3f8376b429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
